// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotifyHub.Api.Source.Infrastructure.Data;

#nullable disable

namespace NotifyHub.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326031427_EditStackTable")]
    partial class EditStackTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotifyHub.Api.Source.Domain.Entities.Call", b =>
                {
                    b.Property<Guid>("CallID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("LandMark")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDttm")
                        .HasColumnType("datetime2");

                    b.HasKey("CallID");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("NotifyHub.Api.Source.Domain.Entities.Stack", b =>
                {
                    b.Property<Guid>("StackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CallID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("StkNbr")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDttm")
                        .HasColumnType("datetime2");

                    b.HasKey("StackID");

                    b.HasIndex("CallID");

                    b.HasIndex("StkNbr")
                        .IsUnique();

                    b.ToTable("Stacks");
                });

            modelBuilder.Entity("NotifyHub.Api.Source.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("UnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvail")
                        .HasColumnType("bit");

                    b.Property<long?>("StkNbr")
                        .HasColumnType("bigint");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnitType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UnitID");

                    b.HasIndex("StkNbr")
                        .IsUnique()
                        .HasFilter("[StkNbr] IS NOT NULL");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("NotifyHub.Api.Source.Domain.Entities.Stack", b =>
                {
                    b.HasOne("NotifyHub.Api.Source.Domain.Entities.Call", null)
                        .WithMany()
                        .HasForeignKey("CallID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
